[book]
authors = ["1KGD"]
language = "en"
src = "src"
title = "Starbloom"

[output.html]
smart-punctuation = true
hash_files = true

[output.html.fold]
enable = true

[output.html.code.hidelines]
python = "~"
